trainset_3d: ['MuCo','Human36M' ] #
trainset_2d: ['MSCOCO', 'CrowdPose'] # 


lr_dec_epoch: [10]
end_epoch: 20
lr: 0.0002
lr_backbone: 0.0002
lr_dec_factor: 1

num_thread: 16
train_batch_size: 8
test_batch_size: 12
enc_layers: 2
dec_layers: 4
weight_decay: 0.01
# max_norm: 0.1
use_cls_token: False
upsample_net: True
update_bbox: True